### ISSUE TITLE
[stable/locust] Is that a problem?

### ISSUE THREAD

**Issue by xumengyan01-cell** [deliveryhero/helm-charts#145]
Thank you for your wonderful job.
I have a problem when I deploy this helm-locust: 
### My Environment
1. AWS EKS a cluster with two nodes
2. EC2 instance type node: m5a.4xlarge
3. Kubernetes version: 1.8
4. ALB: [aws-alb-controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/)
### What I wan to ask
**Here is the log of the slave, I do not know waht's wrong with my setting** 
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/locust/util/exception_handler.py", line 13, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/locust/rpc/zmqrpc.py", line 22, in send
    raise RPCError("ZMQ sent failure") from e
locust.exception.RPCError: ZMQ sent failure
[2021-04-16 04:55:45,511] locust-worker-f968676b4-s7jsf/INFO/locust.util.exception_handler: Exception found on retry 3: -- retry after 5s
[2021-04-16 04:55:45,512] locust-worker-f968676b4-s7jsf/ERROR/locust.util.exception_handler: ZMQ sent failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/locust/rpc/zmqrpc.py", line 20, in send
    self.socket.send(msg.serialize(), zmq.NOBLOCK)
  File "/usr/local/lib/python3.8/site-packages/zmq/green/core.py", line 193, in send
    msg = super(_Socket, self).send(data, flags, copy, track, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/zmq/sugar/socket.py", line 491, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 720, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 767, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/locust/util/exception_handler.py", line 13, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/locust/rpc/zmqrpc.py", line 22, in send
    raise RPCError("ZMQ sent failure") from e
locust.exception.RPCError: ZMQ sent failure
[2021-04-16 04:55:48,432] locust-worker-f968676b4-s7jsf/INFO/locust.util.exception_handler: Retry failed after 3 times.
[2021-04-16 04:55:48,432] locust-worker-f968676b4-s7jsf/ERROR/locust.runners: RPCError found when sending heartbeat: ZMQ sent failure
[2021-04-16 04:55:48,432] locust-worker-f968676b4-s7jsf/INFO/locust.runners: Reset connection to master
[2021-04-16 04:55:48,433] locust-worker-f968676b4-s7jsf/ERROR/locust.runners: RPCError found when receiving from master: ZMQ network broken
[2021-04-16 04:55:50,513] locust-worker-f968676b4-s7jsf/INFO/locust.util.exception_handler: Retry failed after 3 times.
[2021-04-16 04:55:50,513] locust-worker-f968676b4-s7jsf/ERROR/locust.runners: Temporary connection lost to master server: ZMQ sent failure, will retry later.
```
**Here is detail of my node and locust-master/locust-worker**
| ADINESS GATES | NODE | 
|:------------:|:------------:|
| locust-master-5f97c65754-lhd9l     | ip-192-168-128-51.ap-northeast-1.compute.internal       | 
| locust-worker-f968676b4-s7jsf     | ip-192-168-224-255.ap-northeast-1.compute.internal      | 
### Detail about my Cluster
```
root@4ba2d7112384:/src/eks/ansible_code_deploy/locust-cluster/playbook# k get all,cm
NAME                                 READY   STATUS    RESTARTS   AGE
pod/locust-master-5f97c65754-lhd9l   1/1     Running   0          4h45m
pod/locust-worker-f968676b4-s7jsf    1/1     Running   0          4h45m

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
service/kubernetes   ClusterIP   10.100.0.1       <none>        443/TCP                                        5h25m
service/locust       NodePort    10.100.221.232   <none>        5557:30798/TCP,5558:31057/TCP,8089:30481/TCP   4h45m

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/locust-master   1/1     1            1           4h45m
deployment.apps/locust-worker   1/1     1            1           4h45m

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/locust-master-5f97c65754   1         1         1       4h45m
replicaset.apps/locust-worker-f968676b4    1         1         1       4h45m

NAME                                         REFERENCE                  TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/locust   Deployment/locust-worker   <unknown>/40%   1         10        1          4h45m

NAME                                                             SERVICE-NAME   SERVICE-PORT   TARGET-TYPE   AGE
targetgroupbinding.elbv2.k8s.aws/k8s-default-locust-94b94d80e9   locust         8089           ip            4h34m

NAME                               DATA   AGE
configmap/locust-config            1      4h45m
configmap/locust-lib               0      4h45m
configmap/my-loadtest-locustfile   1      4h45m
```

**Comment by xumengyan01-cell** [comment]
This is my first time to ask question at github, maybe I lost some information about this issue. 
I'm waiting for your answer, if you need any more information about my question, please contact me.
Thank you so much.

**Comment by max-rocket-internet** [comment]
Yes it's a problem, it looks like your worker cannot resolve the DNS address of the master in your cluster, `locust`

**Comment by xumengyan01-cell** [comment]
I have resolved the problem, thank you for your answer.@max-rocket-internet

**Comment by xumengyan01-cell** [comment]
@max-rocket-internet 
But I have meet another problem, I don't know is it a problem or I have made a mistake to set it.
### What I want to do
 I want to use ingress to connet the `NodePort `service of locust
### What I have done
Until right now , I have use this helm-chart version `0.9.13` . And, I have tried `nginx-controller in minikube`, and `aws-alb-controller in EKS`. 
### The problem

But I have met the same result with web-ui

![image](https://user-images.githubusercontent.com/67623180/115958330-ffeb4c80-a541-11eb-8304-ed615ddffbcb.png)

and when I try to click `start swarming` , here is the page:

![image](https://user-images.githubusercontent.com/67623180/115958383-3e810700-a542-11eb-942a-67520810c7d5.png)

**Maybe it is not a good choice to use nginx-ingress-controller or aws-alb-controller ? 
I am waiting for your answer, Thank you.**

----
Here the code of my ingress yaml, I am using nginx-ingress-controller in minikube
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              serviceName: my-release-locust
              servicePort: 8089
```
Here is the detail of my node in minikube
```
NAME                                           READY   STATUS    RESTARTS   AGE
pod/my-release-locust-master-bf5847dbf-fqpxz   1/1     Running   0          87m
pod/my-release-locust-worker-b7ff8896f-z9f6j   1/1     Running   0          87m

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
service/kubernetes          ClusterIP   10.96.0.1        <none>        443/TCP                                        9d
service/my-release-locust   NodePort    10.100.239.120   <none>        5557:30660/TCP,5558:30705/TCP,8089:30118/TCP   87m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-release-locust-master   1/1     1            1           87m
deployment.apps/my-release-locust-worker   1/1     1            1           87m

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/my-release-locust-master-bf5847dbf   1         1         1       87m
replicaset.apps/my-release-locust-worker-b7ff8896f   1         1         1       87m
```

**Comment by max-rocket-internet** [comment]
> But I have meet another problem, I don't know is it a problem or I have made a mistake to set it.

I'm sorry, I don't know. Perhaps try repo or support for your ALB ingress.

**Comment by xumengyan01-cell** [comment]
Ok, Thank you so much. Your job really helps me a lot.

**Comment by edisonyang001** [comment]
I have this problem too, you solved it like this？

**Comment by LeBronQ** [comment]
> I have resolved the problem, thank you for your answer.@max-rocket-internet

May I ask how you solved the problem?I also met with the same problem. Thanks a lot!
