### ISSUE TITLE
[stable/locust]  ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by androna-xm** [deliveryhero/helm-charts#154]
I tried to install to minikube the locust with the following command as you proposed :
 `helm install my-release deliveryhero/locust`

but as soon as i start swarming i see these logs in my master node 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/locust/web.py", line 366, in wrapper
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/locust/web.py", line 148, in swarm
    user_count = int(request.form["user_count"])
ValueError: invalid literal for int() with base 10: ''
2021-04-23T10:13:43Z {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '59420', 'HTTP_HOST': 'localhost:8089', (hidden keys: 33)} failed with ValueError
`

How could i solve this?

**Comment by max-rocket-internet** [comment]
I just did this:

```
$ helm install max-test  deliveryhero/locust
NAME: max-test
LAST DEPLOYED: Fri Apr 23 13:06:39 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
## To access the locust master UI
Run this command:

  kubectl --namespace default port-forward service/max-test-locust 8089:8089

Then open in a browser: http://localhost:8089

$ kubectl --namespace default port-forward service/max-test-locust 8089:8089
Forwarding from 127.0.0.1:8089 -> 8089
Forwarding from [::1]:8089 -> 8089
Handling connection for 8089
```

Then start the test in the UI at http://localhost:8089

And it works

![Screenshot 2021-04-23 at 13 08 20](https://user-images.githubusercontent.com/8859277/115863022-28d1eb80-a435-11eb-8c4e-699c6c670e1a.png)

**Comment by max-rocket-internet** [comment]
Are you using the default example or your own locustfile?

**Comment by androna-xm** [comment]
I am using the default example,i didn't change anything , and i have access to the UI. But when i press the "start swarming" i see the error in the master's log and therefore no statistics at the UI. I thought maybe it is due to python's version but still don't know how to fix this.

**Comment by androna-xm** [comment]
Before the error , the logs seem to be fine :
`kubectl logs -f my-release-locust-master-58544cdcb7-dvgzj
[2021-04-23 10:11:47,627] my-release-locust-master-58544cdcb7-dvgzj/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
[2021-04-23 10:11:47,644] my-release-locust-master-58544cdcb7-dvgzj/INFO/locust.main: Starting Locust 1.4.3
[2021-04-23 10:11:47,666] my-release-locust-master-58544cdcb7-dvgzj/INFO/root: Terminal was not a tty. Keyboard input disabled
[2021-04-23 10:12:14,707] my-release-locust-master-58544cdcb7-dvgzj/INFO/locust.runners: Client 'my-release-locust-worker-67f887f95-f5298_ecb240e4e1f645d89a9f18b137786693' reported as ready. Currently 1 clients ready to swarm.
`

**Comment by max-rocket-internet** [comment]
I think the error is `swarm user_count = int(request.form["user_count"]) ValueError: invalid literal for int() with base 10: ''` but I think you will need to debug that yourself or with locust repo as it's not related to this Helm chart 🙂
